### ISSUE TITLE
DateTime::fromNativeDateTime should be aware of timezone

### ISSUE THREAD

**Issue by ajgarlag** [nicolopignatelli/valueobjects#28]
It is possible to build two equals `DateTime` objects from two different native `\DateTime` objects because the `fromNativeDateTime` ignores the `\DateTimeZone`.

```php
$nativeDateTime1 = new \DateTime('2015-02-23 20:30:00', new \DateTimeZone('Europe/Madrid'));
$nativeDateTime2 = new \DateTime('2015-02-23 20:30:00', new \DateTimeZone('Europe/London'));

$voDateTime1 = \ValueObjects\DateTime\DateTime::fromNativeDateTime($nativeDateTime1);
$voDateTime2 = \ValueObjects\DateTime\DateTime::fromNativeDateTime($nativeDateTime2);

var_dump($voDateTime1->sameValueAs($voDateTime2)); //It should be false, but it is true
```

**Comment by ajgarlag** [comment]
@nicolopignatelli I can work on this issue, but I see two alternatives here:

1. Two `\ValueObjects\DateTime\DateTime` have the same value if they represent the same timestamp.
2. Two  `\ValueObjects\DateTime\DateTime` have the same value if they represent the same datetime and timezone.

I'll choose the first approach, so when building from native date time, I would convert them to `UTC` before storing the numeric values.

What do you think about?

**Comment by nicolopignatelli** [comment]
Yeah, sorry, been busy these days.

Why do you want to discard the original timezone? I think this could be confusing for clients that use the api.

**Comment by ajgarlag** [comment]
Well, I'm a very newbie in VO. Here is the problem I see.

Let's suppose, we decide that two `\ValueObjects\DateTime\DateTime` have the same value if they represent the same timestamp (although it breaks BC).
 ```php
$nativeDateTime1 = new \DateTime('2015-03-05 16:38:21', new \DateTimeZone('Asia/Tokyo'));
$nativeDateTime2 = new \DateTime('2015-03-05 02:38:21', new \DateTimeZone('America/New_York'));
var_dump($nativeDateTime1 == $nativeDateTime2); // bool(true)

$voDateTime1 = \ValueObjects\DateTime\DateTime::fromNativeDateTime($nativeDateTime1);
$voDateTime2 = \ValueObjects\DateTime\DateTime::fromNativeDateTime($nativeDateTime2);
```

Now, if we convert the native DateTime to 'UTC' before extracting values, we have:
```php
var_dump($voDateTime1->sameValueAs($voDateTime2)); // bool(true)
var_dump($voDateTime1->getTime()->sameValueAs($voDateTime2->getTime())); // bool(true)
```
But, if we choose to keep the values from the original timezone, we have :
```php
var_dump($voDateTime1->sameValueAs($voDateTime2)); // bool(true)
var_dump($voDateTime1->getTime()->sameValueAs($voDateTime2->getTime())); // bool(false)
```
Maybe, the best option is to introduce a new `DateTimeWithTZ` VO without touching the `DateTime` implementation, so we avoid any BC break, and the user is aware of the consecuences of comparing subvalues of `DateTimeWithTZ`

**Comment by nicolopignatelli** [comment]
I would also be for adding a new VO, but the DateTime one should also be fixed to ignore the timezone.

**Comment by nicolopignatelli** [comment]
We should first agree on the equality condition of the DateTimeWithTz:
same date, same time and same tz?
or same date, same time after we correct the timezones offsets?

I would go for the first and add a new method to also have the second option check

**Comment by ajgarlag** [comment]
I agree. I'll work in a PR
