### ISSUE TITLE
Rename String class

### ISSUE THREAD

**Issue by ajgarlag** [nicolopignatelli/valueobjects#36]
With Scalar Type Hinting merged into PHP7, the word `String` cannot be used as a class name.

**Comment by nicolopignatelli** [comment]
Right. You already have a suggestion for a compatible, yet similar to String name?

**Comment by ajgarlag** [comment]
I'm not very good naming things, but here are some options:

* StringVo
* VoString
* [StringLiteral](https://en.wikipedia.org/wiki/String_literal)

**Comment by nicolopignatelli** [comment]
sorry for the delay. StringLiteral is ok for me.

**Comment by nicolopignatelli** [comment]
Done in #37
