### ISSUE TITLE
Change date and time format output

### ISSUE THREAD

**Issue by MLoureiro** [nicolopignatelli/valueobjects#45]
Hi @nicolopignatelli 

First of all, thanks for the lib :blush: 
I'm starting to use this in our project, and the first thing I've noticed is that the date/time output is hardcoded, there is no simple way to return in another format (at least that I've saw)

So I've did this change: https://github.com/creativesterminal/valueobjects/commit/96ea10ef60bb6e6062741ab8c23163b741793777

If you're interested in merging this to the lib, I can make a PR for it.
Tell me your thoughts

**Comment by TomasVotruba** [comment]
Hey @MLoureiro , thanks for contribution.

If you have already made some work, it's better to discuss over the PR. Look forward to it!

**Comment by MLoureiro** [comment]
@TomasVotruba thanks!  As soon I get a few extra time I'll make the PR

**Comment by sstok** [comment]
Using a static method to change the required input format for ALL OBJECTS is a horrible idea (especially for value object which need to be immutable) and breaks the idea of Domain vs user-input separation.

Say I do the following:

```php
Date::setDateFormat('d-m-Y H:i:s'); // which is actually wrong as a date has no time.

$currentDate = Date::now();

// Some deep layer, expecting the 'Y-m-d' format.
// ...
Date::setDateFormat('Y-m-d');
// ..

echo (string) $currentDate; // echoes in the 'Y-m-d' format, WTF?
```

`Y-m-d H:i:s` is the industries standard for storing datetimes.
If your user presentation or user-input requires something else (which it must certainly will) you need to change the input itself (not how it's processed) or inform how it needs to processed (only for this value).

```php
$currentDate = Date::fromFormat('d-m-Y H:i', '26-9-2015 10:37');
// Kept internally in the `Y-m-d` format.

// Some deep layer, expecting the 'Y-m-d' format.
// (string) $currentDate;
// ...

echo $currentDate->format('d-m-Y H:i:s'); // echoes in the ''d-m-Y H:i:s'' format, YEA!
```

Using static to change the behavior of all objects will lead to some really hard to find bugs, and breaks to many best practices.

**Comment by MLoureiro** [comment]
> Using static to change the behavior of all objects will lead to some really hard to find bugs, and breaks to many best practices.

The idea of static is to change the hardcoded output that cannot be changed.

> especially for value object which need to be immutable

I do agree with you, so how are you formatting the date ValueObject?
Is it like:

```php
$currentDate = Date::now():

$currentDate->toNativeDateTime()->format('Y-m-d');
````

If it is, shouldn't the ValueObject's abstract the inner functionalities of the PHP variables?

**Comment by nicolopignatelli** [comment]
Wouldn't be simple to just override the __toString method in your class?

**Comment by MLoureiro** [comment]
It's possible.
I don't actually like hardcoded stuff, but tbh I'm not sure about the common practices.

**Comment by nicolopignatelli** [comment]
The whole library has the only purpose to "help developers using and undestanding immutable objects."
It's unlikely that fine grained features like this would be added to the library.

**Comment by MLoureiro** [comment]
Got it.
