### ISSUE TITLE
Should I use this library? - proposed changes

### ISSUE THREAD

**Issue by AGmakonts** [nicolopignatelli/valueobjects#64]
I understand the purpose of suggesting that this library should be considered as an educational resource but it's in my opinion too useful to be "thrown away" in favour of dedicated implementation. Of course, everybody should implement special VO for most cases but to store and validate simpler values this library is perfect. 

My suggestion is to get rid of this section in favor of something encouraging to extending existing classes and using them as dependencies in dedicated VOs.

**Comment by greg0ire** [comment]
I guess that's a no? :/
