### ISSUE TITLE
WeekDay numeration

### ISSUE THREAD

**Issue by nnnikolay** [nicolopignatelli/valueobjects#67]
I think it make sense to have a numeric day representation in that object as well.
Currently it's really weird getOrdinal instead of predefined way, you know some countries consider Sunday as a first day of the week and has numeration as 0 and some other as 7, so it would be great to have such feature. What do you think about it ?

**Comment by nicolopignatelli** [comment]
Hi, this library is only for educational purposes, as stated in the README, therefore applying changes that could make sense only in some domains while not in others is out of its scope.
I suggest you to implement the logic for dynamically converting weekdays to numbers in your project's VOs, if this is relevant to you (e.g. if you have to deal with countries that have different weekdays enumerations)
