### ISSUE TITLE
Unclear exception messages due to bug in some value objects.

### ISSUE THREAD

**Issue by bertramakers** [nicolopignatelli/valueobjects#78]
A colleague (@lucwollants) and I noticed that we sometimes get "strange" exception messages for invalid value objects, for example:

```php
$natural = new Natural(-8);
```

Result:

> InvalidNativeArgumentException in Natural.php line 25: Argument "" is invalid. Allowed types for argument are "int (>=0)".

Expected result:

> InvalidNativeArgumentException in Natural.php line 25: Argument "-8" is invalid. Allowed types for argument are "int (>=0)".

This seems to be caused by using the return value of `filter_var()` as `$value` in the exception message, while `$value` is always `false` when throwing the exception. (And `false` is casted to an empty string). https://github.com/nicolopignatelli/valueobjects/blob/master/src/Number/Natural.php#L22-L26

This pattern seems to be repeated in other classes as well, for example in `Integer`: https://github.com/nicolopignatelli/valueobjects/blob/master/src/Number/Integer.php#L18-L22

At this point it's unclear to us how many classes are affected, but I guess most will follow this pattern.

If okay with you we can try to fix this ourselves and submit a PR for you to review, but we wanted to check first if it's something you'd accept because depending on the number of classes affected it may be quite some work.

Our suggested approach would be something like this:

```php
public function __construct($value)
{
    $filteredValue = filter_var($value, FILTER_VALIDATE_INT);
    if (false === $filteredValue) {
        throw new InvalidNativeArgumentException($value, array('int'));
    }
    parent::__construct($filteredValue);
}
```

**Comment by LucWollants** [comment]
The current unit test for Natural doesn't take into account the expected exception message:
https://github.com/nicolopignatelli/valueobjects/blob/master/tests/Number/NaturalTest.php#L10

This is something that can be handled together with the 'proposed fix' for the unclear exception messages.

**Comment by nicolopignarocket** [comment]
I'd definitely accept a PR for that. What you say is true, we should pass the original value to the exception class, not the filtered one.

**Comment by nicolopignatelli** [comment]
I'd definitely accept a PR for that. What you say is true, we should pass the original value to the exception class, not the filtered one.
